[package]
name = "vsr-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
env_logger = "0.9.1"
log = "0.4.17"
parking_lot = "0.12.1"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
